### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by javipalanca** [DinoThor/PyJabber#12]
Click is missing from the dependencies list.

Error:
❯ python -m pyjabber --help
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/jpalanca/anaconda3/envs/testspade/lib/python3.11/site-packages/pyjabber/__main__.py", line 1, in <module>
    import click
ModuleNotFoundError: No module named 'click'

**Comment by DinoThor** [comment]
Fixed a68d72e
