### ISSUE TITLE
Error connecting

### ISSUE THREAD

**Issue by javipalanca** [DinoThor/PyJabber#14]
Connecting an agent to the server is too slow (some seconds) and the it throws this error:

`2024-05-30 15:26:30.718 | DEBUG    | pyjabber.network.XMLParser:startElementNS:57 - Start element NS: ('jabber:client', 'presence')
Error calling eof_received()
protocol: <asyncio.sslproto.SSLProtocol object at 0x10ce0a7d0>
transport: <_SelectorSocketTransport closing fd=27 read=idle write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/Users/jpalanca/anaconda3/envs/testspade/lib/python3.11/asyncio/sslproto.py", line 807, in _call_eof_received
    keep_open = self._app_protocol.eof_received()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jpalanca/anaconda3/envs/testspade/lib/python3.11/site-packages/pyjabber/network/XMLProtocol.py", line 126, in eof_received
    self._xml_parser.feed(f"<presence type='unavailable' />".encode())
  File "/Users/jpalanca/anaconda3/envs/testspade/lib/python3.11/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "/private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_bch2rdl72g/croot/python-split_1677696108832/work/Modules/pyexpat.c", line 416, in StartElement
  File "/Users/jpalanca/anaconda3/envs/testspade/lib/python3.11/xml/sax/expatreader.py", line 369, in start_element_ns
    self._cont_handler.startElementNS(pair, None,
  File "/Users/jpalanca/anaconda3/envs/testspade/lib/python3.11/site-packages/pyjabber/network/XMLParser.py", line 78, in startElementNS
    raise Exception()
Exception
2024-05-30 15:26:30.719 | INFO     | pyjabber.network.XMLProtocol:connection_lost:78 - Connection lost from None: Reason 
2024-05-30 15:26:30.720 | INFO     | pyjabber.network.XMLProtocol:connection_lost:85 - Connection lost after EOF recived`

**Comment by DinoThor** [comment]
Fixed
